spring.application.name=registro-cultural-web
server.port=8080

# SQLite - volumen montado en /data para no colisionar con el jar en /app
spring.datasource.url=jdbc:sqlite:/data/registro_cultural.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Subida de portadas (max 10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Directorio de portadas - dentro del volumen
app.covers-dir=/data/covers

# TMDB - valores directos
tmdb.bearer-token=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI1MmQyNGUzNDhjMTMxOTY2N2FkOWIyZWVjODM1MjNiYiIsIm5iZiI6MTcxMTI3NzA2Mi40NjUsInN1YiI6IjY2MDAwNDA2Yjg0Y2RkMDE3ZGY1Mzk2MSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.69mnb1wZVXOOhp2LAV5WeXRDxfLVLH-qyB2PUctCDiU
tmdb.api-key=52d24e348c1319667ad9b2eec83523bb

# Comic Vine
comicvine.api-key=ed7946debd9f28bb4e4ca62f6722c269c24361ae
comicvine.base-url=https://comicvine.gamespot.com/api
